# Generated by Django 4.0.2 on 2022-02-26 18:50

from django.db import migrations, models
import django.db.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('titile', models.TextField()),
                ('body', models.TextField()),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='api.section')),
            ],
        ),
    ]
