# Generated by Django 4.0.2 on 2022-02-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='titile',
            new_name='title',
        ),
    ]
